# Activity 8


Clint Egargo

[Source code](https://github.com/egargo/study/blob/master/ml/swiss_banknote_conterfeit_detection_egargo_clint.ipynb)

Dataset: [Swiss banknote conterfeit detection](https://www.kaggle.com/datasets/chrizzles/swiss-banknote-conterfeit-detection)

In [408]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [409]:
import pandas as pd

# Uncomment if running in Kaggle.
# df = pd.read_csv('/kaggle/input/swiss-banknote-conterfeit-detection/banknotes.csv')

df = pd.read_csv('./datasets/banknotes.csv')

In [410]:
df

conterfeit  Length   Left  Right  Bottom   Top  Diagonal
0             0   214.8  131.0  131.1     9.0   9.7     141.0
1             0   214.6  129.7  129.7     8.1   9.5     141.7
2             0   214.8  129.7  129.7     8.7   9.6     142.2
3             0   214.8  129.7  129.6     7.5  10.4     142.0
4             0   215.0  129.6  129.7    10.4   7.7     141.8
..          ...     ...    ...    ...     ...   ...       ...
195           1   215.0  130.4  130.3     9.9  12.1     139.6
196           1   215.1  130.3  129.9    10.3  11.5     139.7
197           1   214.8  130.3  130.4    10.6  11.1     140.0
198           1   214.7  130.7  130.8    11.2  11.2     139.4
199           1   214.3  129.9  129.9    10.2  11.5     139.6

[200 rows x 7 columns]

In [411]:
df.count

<bound method DataFrame.count of      conterfeit  Length   Left  Right  Bottom   Top  Diagonal
0             0   214.8  131.0  131.1     9.0   9.7     141.0
1             0   214.6  129.7  129.7     8.1   9.5     141.7
2             0   214.8  129.7  129.7     8.7   9.6     142.2
3             0   214.8  129.7  129.6     7.5  10.4     142.0
4             0   215.0  129.6  129.7    10.4   7.7     141.8
..          ...     ...    ...    ...     ...   ...       ...
195           1   215.0  130.4  130.3     9.9  12.1     139.6
196           1   215.1  130.3  129.9    10.3  11.5     139.7
197           1   214.8  130.3  130.4    10.6  11.1     140.0
198           1   214.7  130.7  130.8    11.2  11.2     139.4
199           1   214.3  129.9  129.9    10.2  11.5     139.6

[200 rows x 7 columns]>

In [412]:
df.isna().sum()

conterfeit    0
Length        0
Left          0
Right         0
Bottom        0
Top           0
Diagonal      0
dtype: int64

In [413]:
df.describe()

conterfeit      Length        Left       Right      Bottom         Top  \
count  200.000000  200.000000  200.000000  200.000000  200.000000  200.000000   
mean     0.500000  214.896000  130.121500  129.956500    9.417500   10.650500   
std      0.501255    0.376554    0.361026    0.404072    1.444603    0.802947   
min      0.000000  213.800000  129.000000  129.000000    7.200000    7.700000   
25%      0.000000  214.600000  129.900000  129.700000    8.200000   10.100000   
50%      0.500000  214.900000  130.200000  130.000000    9.100000   10.600000   
75%      1.000000  215.100000  130.400000  130.225000   10.600000   11.200000   
max      1.000000  216.300000  131.000000  131.100000   12.700000   12.300000   

         Diagonal  
count  200.000000  
mean   140.483500  
std      1.152266  
min    137.800000  
25%    139.500000  
50%    140.450000  
75%    141.500000  
max    142.400000

In [414]:
X = df.drop(['conterfeit'], axis=1)
y = df[['conterfeit']]

In [415]:
X

Length   Left  Right  Bottom   Top  Diagonal
0     214.8  131.0  131.1     9.0   9.7     141.0
1     214.6  129.7  129.7     8.1   9.5     141.7
2     214.8  129.7  129.7     8.7   9.6     142.2
3     214.8  129.7  129.6     7.5  10.4     142.0
4     215.0  129.6  129.7    10.4   7.7     141.8
..      ...    ...    ...     ...   ...       ...
195   215.0  130.4  130.3     9.9  12.1     139.6
196   215.1  130.3  129.9    10.3  11.5     139.7
197   214.8  130.3  130.4    10.6  11.1     140.0
198   214.7  130.7  130.8    11.2  11.2     139.4
199   214.3  129.9  129.9    10.2  11.5     139.6

[200 rows x 6 columns]

In [416]:
y

conterfeit
0             0
1             0
2             0
3             0
4             0
..          ...
195           1
196           1
197           1
198           1
199           1

[200 rows x 1 columns]

In [417]:
trainX, testX, trainY, testY = train_test_split(X, y, test_size=0.33)

In [418]:
trainX.isnull()

Length   Left  Right  Bottom    Top  Diagonal
106   False  False  False   False  False     False
69    False  False  False   False  False     False
58    False  False  False   False  False     False
96    False  False  False   False  False     False
53    False  False  False   False  False     False
..      ...    ...    ...     ...    ...       ...
98    False  False  False   False  False     False
147   False  False  False   False  False     False
159   False  False  False   False  False     False
75    False  False  False   False  False     False
135   False  False  False   False  False     False

[134 rows x 6 columns]

# Decision Tree

In [419]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(trainX, trainY)

DecisionTreeClassifier()

In [420]:
predY = dt.predict(testX)

In [421]:
cm = confusion_matrix(testY, predY)
cm

array([[34,  0],
       [ 1, 31]])

In [422]:
tp, fp, fn = cm.ravel()[:3]
tn = cm.ravel()[-1]

precision = tp/(tp+fp)
recall = tp/(tp+fn)
specificity = tn/(fp+tn)
f1= 2* (precision*recall)/(precision+recall)

precision, recall, specificity , f1

(1.0, 0.9714285714285714, 1.0, 0.9855072463768115)

# SVM

In [423]:
from sklearn.svm import SVC

svm = SVC(kernel='linear')
svm.fit(trainX, trainY.values.ravel())

SVC(kernel='linear')

In [424]:
predY = svm.predict(testX)

In [425]:
cm = confusion_matrix(testY, predY)
cm

array([[34,  0],
       [ 0, 32]])

In [426]:
tp, fp, fn = cm.ravel()[:3]
tn = cm.ravel()[-1]

precision = tp/(tp+fp)
recall = tp/(tp+fn)
specificity = tn/(fp+tn)
f1= 2* (precision*recall)/(precision+recall)
precision, recall, specificity , f1

(1.0, 1.0, 1.0, 1.0)

# Naive Bayes

In [427]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(trainX, trainY.values.ravel())

GaussianNB()

In [428]:
predY = nb.predict(testX)

In [429]:
cm = confusion_matrix(testY, predY)
cm

array([[34,  0],
       [ 0, 32]])

In [430]:
tp, fp, fn = cm.ravel()[:3]
tn = cm.ravel()[-1]

precision = tp/(tp+fp)
recall = tp/(tp+fn)
specificity = tn/(fp+tn)
f1= 2* (precision*recall)/(precision+recall)
precision, recall, specificity , f1

(1.0, 1.0, 1.0, 1.0)